/**
 * Generated by Protocol Workbench browser action recorder.
 * Run with: node browser-flow.js
 * To repeat: BROWSER_REPEAT=5 node browser-flow.js
 * To provide values: BROWSER_DATA_FILE=browser-data.json node browser-flow.js
 * Login state: BROWSER_STORAGE_STATE="storage-state.json" node browser-flow.js
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright");
const { TempMailApi } = require("./temp-mail-api");
const { BitBrowserClient } = require("./bitbrowser-client");

function parseBrowserIds(value) {
  if (Array.isArray(value)) return value.map(String).map((id) => id.trim()).filter(Boolean);
  return String(value || "").split(/[,\s]+/).map((id) => id.trim()).filter(Boolean);
}

function resolveRuntimeFile(file) {
  const value = String(file || "").trim();
  if (!value) return "";
  return path.isAbsolute(value) ? value : path.resolve(process.env.APP_HOME || process.cwd(), value);
}

function loadBitBrowserSettings() {
  const file = process.env.BITBROWSER_CONFIG_FILE || "bitbrowser.config.json";
  const configFile = path.isAbsolute(file)
    ? file
    : path.resolve(process.env.APP_HOME || process.cwd(), file);
  let fileConfig = {};
  if (fs.existsSync(configFile)) {
    const parsed = JSON.parse(fs.readFileSync(configFile, "utf8"));
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error(`BitBrowser 配置文件必须是 JSON 对象：${configFile}`);
    }
    fileConfig = parsed;
  }
  const envIds = parseBrowserIds(process.env.BITBROWSER_BROWSER_IDS || process.env.BITBROWSER_BROWSER_ID);
  return {
    provider: String(process.env.BROWSER_PROVIDER || fileConfig.provider || "local").toLowerCase(),
    apiUrl: String(process.env.BITBROWSER_API_URL || fileConfig.apiUrl || "http://127.0.0.1:54345").replace(/\/+$/, ""),
    browserIds: envIds.length ? envIds : parseBrowserIds(fileConfig.browserIds),
    queue: process.env.BITBROWSER_QUEUE === undefined ? fileConfig.queue !== false : process.env.BITBROWSER_QUEUE !== "false",
    parallel: process.env.BROWSER_PARALLEL === undefined ? fileConfig.parallel === true : process.env.BROWSER_PARALLEL === "true",
    closeOnExit: process.env.BITBROWSER_CLOSE_ON_EXIT === undefined ? fileConfig.closeOnExit === true : process.env.BITBROWSER_CLOSE_ON_EXIT === "true",
    apiTimeoutMs: Number(process.env.BITBROWSER_API_TIMEOUT_MS || fileConfig.apiTimeoutMs || 15000),
    proxyUrl: String(process.env.BITBROWSER_PROXY_URL || fileConfig.proxyUrl || "").trim(),
  };
}

const bitBrowser = loadBitBrowserSettings();

const config = {
  timeoutMs: Number(process.env.BROWSER_TIMEOUT_MS || 30000),
  headless: process.env.BROWSER_HEADLESS === "true",
  provider: bitBrowser.provider,
  bitbrowser: bitBrowser,
  cartUrl: process.env.BROWSER_CART_URL || process.env.BROWSER_START_URL || "https://www.weee.com/en/cart",
  checkoutUrl: process.env.BROWSER_CHECKOUT_URL || "https://www.weee.com/en/order/checkout?cart_domain=grocery",
  checkoutMode: (process.env.BROWSER_CHECKOUT_MODE || "prepare").toLowerCase(),
  paymentCardFile: resolveRuntimeFile(process.env.PAYMENT_CARD_FILE || "cards.txt"),
  paymentSavedFile: resolveRuntimeFile(process.env.PAYMENT_SAVED_FILE || "saved-cards.txt"),
  paymentMaxSaves: Math.max(1, Number(process.env.PAYMENT_MAX_SAVES_PER_MAILBOX || 3)),
  paymentMaxRateLimitRestarts: Math.max(1, Number(process.env.PAYMENT_MAX_RATE_LIMIT_RESTARTS || 20)),
  networkIdleTimeoutMs: Number(process.env.BROWSER_NETWORK_IDLE_TIMEOUT_MS || 10000),
  domStableMs: Number(process.env.BROWSER_DOM_STABLE_MS || 300),
  domStableTimeoutMs: Number(process.env.BROWSER_DOM_STABLE_TIMEOUT_MS || 5000),
};

async function firstVisible(page, selectors) {
  for (const selector of selectors) {
    const locator = page.locator(selector).first();
    if (await locator.isVisible().catch(() => false)) return locator;
  }
  return null;
}

async function lastVisible(page, selectors) {
  for (const selector of selectors) {
    const locator = page.locator(selector);
    const count = await locator.count();
    for (let index = count - 1; index >= 0; index -= 1) {
      const candidate = locator.nth(index);
      if (await candidate.isVisible().catch(() => false)) return candidate;
    }
  }
  return null;
}

async function isUsable(locator) {
  if (!await locator.isVisible().catch(() => false)) return false;
  return locator.evaluate((element) => {
    let current = element;
    while (current) {
      if (current.getAttribute?.("aria-hidden") === "true") return false;
      const style = window.getComputedStyle(current);
      if (style.display === "none" || style.visibility === "hidden" || style.pointerEvents === "none") {
        // Radix applies pointer-events:none to <body> while a modal is open;
        // a modal child with pointer-events:auto remains interactive.
        if (current !== document.body && current !== document.documentElement) return false;
      }
      current = current.parentElement;
    }
    return true;
  }).catch(() => false);
}

async function lastUsable(page, selectors) {
  for (const selector of selectors) {
    const locator = page.locator(selector);
    const count = await locator.count();
    for (let index = count - 1; index >= 0; index -= 1) {
      const candidate = locator.nth(index);
      if (await isUsable(candidate)) return candidate;
    }
  }
  return null;
}

async function waitForVisible(page, selectors, timeoutMs = config.timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const match = await lastVisible(page, selectors);
    if (match) return match;
    await page.waitForTimeout(150);
  }
  return null;
}

async function waitForUsable(page, selectors, timeoutMs = config.timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const match = await lastUsable(page, selectors);
    if (match) return match;
    await page.waitForTimeout(150);
  }
  return null;
}

async function closeActiveLoginDialog(page) {
  const dialogs = page.locator('[role="dialog"]');
  for (let index = await dialogs.count() - 1; index >= 0; index -= 1) {
    const dialog = dialogs.nth(index);
    if (!await isUsable(dialog)) continue;
    const close = dialog.locator('[data-testid="wid-modal-btn-close"]').last();
    if (await isUsable(close)) {
      await close.click({ force: true });
      await page.waitForTimeout(500);
      await waitForDomStable(page);
      return true;
    }
  }
  return false;
}

async function hasUsableDialog(page) {
  const dialogs = page.locator('[role="dialog"]');
  for (let index = await dialogs.count() - 1; index >= 0; index -= 1) {
    if (await isUsable(dialogs.nth(index))) return true;
  }
  return false;
}

async function clickCartCheckout(page) {
  if (/\/order\/checkout(?:[/?]|$)/i.test(page.url())) return true;
  let checkout = await waitForVisible(page, [
    ".h-1500",
    '[data-testid="wid-cart-summary-checkout"]',
    'button[aria-label="Checkout"]',
  ], config.timeoutMs);
  if (!checkout) {
    // Closing a login layer can leave Weee on its checkout route with no
    // cart button mounted. Return to the cart, then perform the requested
    // second Checkout click against a fresh DOM.
    await page.goto(interpolate(config.cartUrl, {}), {
      waitUntil: "domcontentloaded",
      timeout: config.timeoutMs,
    });
    await waitForPageSettled(page);
    checkout = await waitForVisible(page, [
      ".h-1500",
      '[data-testid="wid-cart-summary-checkout"]',
      'button[aria-label="Checkout"]',
    ], config.timeoutMs);
  }
  if (!checkout) throw new Error("购物车 Checkout 按钮未出现，无法重新打开登录弹窗。");
  await checkout.click({ force: true, timeout: config.timeoutMs });
  await page.waitForTimeout(1200);
  await waitForPageSettled(page);
  if (/\/order\/checkout(?:[/?]|$)/i.test(page.url())) return true;
  const signalDeadline = Date.now() + Math.min(config.timeoutMs, 10000);
  while (Date.now() < signalDeadline) {
    if (/\/order\/checkout(?:[/?]|$)/i.test(page.url())) return true;
    if (await hasUsableDialog(page)) return false;
    await page.waitForTimeout(250);
  }
  return /\/order\/checkout(?:[/?]|$)/i.test(page.url());
}

async function waitForDomStable(page, timeoutMs = config.domStableTimeoutMs) {
  await page.evaluate(({ stableMs, timeoutMs }) => new Promise((resolve) => {
    if (!document?.documentElement || typeof MutationObserver === "undefined") {
      resolve();
      return;
    }
    let settledTimer;
    let finished = false;
    let observer;
    const finish = () => {
      if (finished) return;
      finished = true;
      clearTimeout(settledTimer);
      observer?.disconnect();
      resolve();
    };
    const schedule = () => {
      clearTimeout(settledTimer);
      settledTimer = setTimeout(finish, stableMs);
    };
    observer = new MutationObserver(schedule);
    observer.observe(document.documentElement, { subtree: true, childList: true, attributes: true });
    setTimeout(finish, timeoutMs);
    schedule();
  }), { stableMs: config.domStableMs, timeoutMs }).catch(() => {});
}

async function waitForPageSettled(page) {
  await page.waitForLoadState("domcontentloaded", { timeout: config.timeoutMs }).catch(() => {});
  if (config.networkIdleTimeoutMs > 0) {
    await page.waitForLoadState("networkidle", { timeout: config.networkIdleTimeoutMs }).catch(() => {});
  }
  await waitForDomStable(page);
}

function paymentData(data = {}) {
  const payment = data.payment || {};
  return {
    cardNumber: String(payment.cardNumber ?? process.env.PAYMENT_CARD_NUMBER ?? "").trim(),
    expirationDate: String(payment.expirationDate ?? process.env.PAYMENT_EXPIRATION_DATE ?? "").trim(),
    cvv: String(payment.cvv ?? process.env.PAYMENT_CVV ?? "").trim(),
    postalCode: String(payment.postalCode ?? process.env.PAYMENT_POSTAL_CODE ?? "").trim(),
  };
}

function parsePaymentCardLine(line, lineNumber) {
  const raw = String(line || "").trim();
  if (!raw || raw.startsWith("#")) return null;
  const match = raw.match(/^([0-9]+)\|([0-9]{2})\|([0-9]{4})$/);
  if (!match) {
    throw new Error(`卡片文件第 ${lineNumber} 行格式不正确，应为 cardNumber|MM|YYYY，例如 5178058585981007|02|2030。`);
  }
  return {
    raw,
    cardNumber: match[1],
    expirationDate: `${match[2]}${match[3].slice(-2)}`,
  };
}

function loadPaymentCards() {
  if (!config.paymentCardFile || !fs.existsSync(config.paymentCardFile)) return [];
  const cards = [];
  for (const [index, line] of fs.readFileSync(config.paymentCardFile, "utf8").split(/\r?\n/).entries()) {
    const card = parsePaymentCardLine(line, index + 1);
    if (card) cards.push(card);
  }
  return cards;
}

function parseProxyUrl(value) {
  const raw = String(value || "").trim();
  if (!raw) return null;
  let parsed;
  try {
    parsed = new URL(raw);
  } catch {
    throw new Error("BITBROWSER_PROXY_URL 格式不正确，应为 socks5h://用户名:密码@主机:端口。");
  }
  const protocol = parsed.protocol.replace(/:$/, "").toLowerCase();
  if (!["socks5h", "socks5", "http", "https"].includes(protocol)) {
    throw new Error(`不支持的代理协议：${protocol}。可用 socks5h、socks5、http、https。`);
  }
  if (!parsed.hostname || !parsed.port) throw new Error("BITBROWSER_PROXY_URL 缺少代理主机或端口。");
  return {
    proxyMethod: 2,
    proxyType: protocol === "socks5h" ? "socks5" : protocol,
    host: parsed.hostname,
    port: Number(parsed.port),
    proxyUserName: decodeURIComponent(parsed.username || ""),
    proxyPassword: decodeURIComponent(parsed.password || ""),
  };
}

function recordSavedPaymentCard(card) {
  if (!config.paymentSavedFile || !card?.raw) return;
  fs.mkdirSync(path.dirname(config.paymentSavedFile), { recursive: true });
  const existing = fs.existsSync(config.paymentSavedFile)
    ? fs.readFileSync(config.paymentSavedFile, "utf8").split(/\r?\n/).map((line) => line.trim()).filter(Boolean)
    : [];
  if (existing.includes(card.raw)) return;
  fs.appendFileSync(config.paymentSavedFile, `${card.raw}\n`, { mode: 0o600 });
  fs.chmodSync(config.paymentSavedFile, 0o600);
}

function assertPaymentData(payment) {
  const missing = Object.entries(payment).filter(([, value]) => !value).map(([key]) => key);
  if (missing.length) {
    throw new Error(`支付表单缺少本地配置：${missing.join(", ")}。请通过 BROWSER_DATA_FILE 的 payment 字段或本机 .env 提供，不要把卡号写进脚本。`);
  }
}

async function fillBraintreeField(page, frameId, label, value) {
  const field = page.frameLocator(`iframe#${frameId}`).getByLabel(label).first();
  await field.waitFor({ state: "visible", timeout: config.timeoutMs });
  await field.fill(value, { timeout: config.timeoutMs });
  await waitForPageSettled(page);
}

async function openCheckoutPaymentPanel(page, data = {}) {
  await page.goto(interpolate(config.checkoutUrl, data), {
    waitUntil: "domcontentloaded",
    timeout: config.timeoutMs,
  });
  await waitForPageSettled(page);

  const paymentMethod = page.getByTestId("wid-checkout-payment-panel-payment-method-add-text").first();
  await paymentMethod.waitFor({ state: "visible", timeout: config.timeoutMs });
  await paymentMethod.click({ timeout: config.timeoutMs });
  await waitForPageSettled(page);
}

async function openAddCardForm(page) {
  let addCard = page.getByTestId("btn-add-ebt-card").first();
  if (!await addCard.isVisible().catch(() => false)) {
    const paymentMethod = page.getByTestId("wid-checkout-payment-panel-payment-method-add-text").first();
    await paymentMethod.waitFor({ state: "visible", timeout: config.timeoutMs });
    await paymentMethod.click({ timeout: config.timeoutMs });
    await waitForPageSettled(page);
    addCard = page.getByTestId("btn-add-ebt-card").first();
  }
  await addCard.waitFor({ state: "visible", timeout: config.timeoutMs });
  await addCard.click({ timeout: config.timeoutMs });
  await waitForPageSettled(page);
}

async function paymentCardCount(page) {
  return page.locator('div[data-testid="wid-checkout-payment-list-content-wrapper-card-item-text"]').count();
}

function isPaymentAttachUrl(url) {
  return /\/ec\/payment\/card\/braintree\/profile\/attach\/v3(?:[?#]|$)/i.test(String(url || ""));
}

function parseJsonMaybe(text) {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

function isFrequentBindAttempt(payload) {
  const message = String(payload?.message || payload?.msg || "");
  return payload?.message_id === "PY10122" ||
    /The number of attempts to bind the card is too frequent\. Please try again after 24 hours\./i.test(message) ||
    /attempts to bind the card is too frequent/i.test(message);
}

async function readPaymentAttachResponse(response) {
  if (!response) return null;
  const text = await response.text().catch(() => "");
  const payload = parseJsonMaybe(text);
  return {
    url: response.url(),
    status: response.status(),
    payload,
    rateLimited: isFrequentBindAttempt(payload),
  };
}

async function savePaymentCard(page, data = {}, card = null) {
  const payment = {
    ...paymentData(data),
    ...(card ? {
      cardNumber: card.cardNumber,
      expirationDate: card.expirationDate,
    } : {}),
  };
  assertPaymentData(payment);
  const beforeCount = await paymentCardCount(page);
  await fillBraintreeField(page, "braintree-hosted-field-number", "Credit Card Number", payment.cardNumber);
  await fillBraintreeField(page, "braintree-hosted-field-expirationDate", "Expiration Date", payment.expirationDate);
  await fillBraintreeField(page, "braintree-hosted-field-cvv", "CVV", payment.cvv);
  await fillBraintreeField(page, "braintree-hosted-field-postalCode", "Postal Code", payment.postalCode);

  const saveCard = page.getByTestId("btn-save-braintree-card").first();
  await saveCard.waitFor({ state: "visible", timeout: config.timeoutMs });
  const attachResponsePromise = page.waitForResponse(
    (response) => isPaymentAttachUrl(response.url()),
    { timeout: config.timeoutMs },
  ).then(readPaymentAttachResponse).catch(() => null);
  await saveCard.click({ timeout: config.timeoutMs });
  await waitForPageSettled(page);
  const attachResponse = await attachResponsePromise;
  if (attachResponse?.payload?.message_id === "PY10114") {
    return {
      stage: "payment-next-card",
      saved: false,
      nextCard: true,
      beforeCount,
      afterCount: beforeCount,
      messageId: "PY10114",
    };
  }
  if (attachResponse?.rateLimited) {
    console.warn("[支付] Weee 返回绑卡过于频繁，准备清理缓存并更换临时邮箱。");
    return {
      stage: "payment-rate-limited",
      saved: false,
      rateLimited: true,
      beforeCount,
      afterCount: beforeCount,
      messageId: attachResponse.payload?.message_id,
      message: attachResponse.payload?.message,
    };
  }
  const deadline = Date.now() + config.timeoutMs;
  let afterCount = beforeCount;
  while (Date.now() < deadline) {
    afterCount = await paymentCardCount(page);
    if (afterCount > beforeCount) break;
    await page.waitForTimeout(250);
  }
  const saved = afterCount > beforeCount;
  if (saved && card) recordSavedPaymentCard(card);
  return {
    stage: saved ? "payment-saved" : "payment-not-recorded",
    saved,
    beforeCount,
    afterCount,
  };
}

async function runCheckoutSteps(page, data = {}, card = null) {
  if (config.checkoutMode === "cart" || config.checkoutMode === "none") {
    return { stage: "cart" };
  }

  if (!["prepare", "payment"].includes(config.checkoutMode)) {
    throw new Error(`不支持的 BROWSER_CHECKOUT_MODE：${config.checkoutMode}。可用值为 cart、prepare、payment。`);
  }

  await openCheckoutPaymentPanel(page, data);
  await openAddCardForm(page);

  if (config.checkoutMode === "prepare") {
    return { stage: "payment-form" };
  }

  return savePaymentCard(page, data, card);
}

async function signInAndGetCode(page, email) {
  await page.goto(config.cartUrl, { waitUntil: "domcontentloaded", timeout: config.timeoutMs });
  await page.waitForTimeout(3000);
  const rejectCookies = await firstVisible(page, [
    '[data-testid*="reject" i]',
    'button:has-text("Reject All")',
  ]);
  if (rejectCookies) {
    await rejectCookies.click();
    await page.waitForTimeout(250);
  }
  const addButton = page.locator(".w-9").first();
  await addButton.waitFor({ state: "visible", timeout: config.timeoutMs });
  await addButton.click();
  await page.waitForTimeout(1200);
  await waitForPageSettled(page);

  // The checkout click animates a second dialog over the first one. Wait for
  // that transition and for the dialog's DOM to finish mounting.
  if (await clickCartCheckout(page)) {
    // An existing BitBrowser profile can already be signed in. Checkout
    // navigates directly without mounting the email dialog.
    return false;
  }

  // Weee can briefly render two login dialogs. The second one is appended on
  // top of the first and its aria-hidden base dialog can still look visible to
  // Playwright. Only use controls whose ancestor dialog is interactive.
  const emailSelectors = [
    '[data-testid="wid-login-email-input"]',
    '[data-testid="wid-ftu-login-method-dialog-login-email-input-input"]',
    'input[autocomplete=email]',
    'input[name=email][placeholder*="email" i]',
    'input[type=email][placeholder*="email" i]',
  ];
  const emailMethodSelectors = [
    '[data-testid="wid-ftu-login-method-dialog-email"]',
    'button:has-text("Continue with email")',
    'text=Continue with email',
  ];
  let emailInput = await waitForUsable(page, emailSelectors, 5000);
  if (!emailInput) {
    // No usable email input means the upper duplicate dialog is blocking the
    // first form. Close that active dialog, then use the first form's arrow.
    await closeActiveLoginDialog(page);
    emailInput = await waitForUsable(page, emailSelectors, 5000);
    if (!emailInput && !await hasUsableDialog(page)) {
      // Closing the duplicate can also dismiss both dialogs. Re-open Checkout
      // so Weee mounts a fresh login dialog before we try the email field.
      if (await clickCartCheckout(page)) return false;
      emailInput = await waitForUsable(page, emailSelectors, config.timeoutMs);
    }
  }
  if (!emailInput) {
    const emailMethod = await waitForUsable(page, emailMethodSelectors, config.timeoutMs);
    if (emailMethod) {
      await emailMethod.click({ force: true });
      await page.waitForTimeout(500);
      await waitForPageSettled(page);
    }
    emailInput = await waitForUsable(page, emailSelectors, config.timeoutMs);
  }
  if (!emailInput) throw new Error("购物车登录弹窗未出现邮箱输入框。");
  try {
    await emailInput.fill(email);
  } catch (error) {
    // A duplicate dialog can finish its animation after the first lookup.
    // Re-resolve the topmost input once before reporting a real failure.
    const refreshedInput = await lastUsable(page, [
      '[data-testid="wid-login-email-input"]',
      '[data-testid="wid-ftu-login-method-dialog-login-email-input-input"]',
      'input[autocomplete=email]',
      'input[name=email][placeholder*="email" i]',
      'input[type=email][placeholder*="email" i]',
    ]);
    if (!refreshedInput) throw error;
    await refreshedInput.fill(email);
    emailInput = refreshedInput;
  }

  const send = await waitForUsable(page, [
    '[data-testid="wid-ftu-login-method-dialog-login-email-input-button"]',
    '[data-testid="wid-login-email-button"]',
  ], config.timeoutMs);
  if (!send) throw new Error("登录弹窗的发送按钮未出现。");
  await send.click();
  const verifyInputSelectors = [
    'input[data-testid^="wid-valid-code-input-"]',
    'input[name*=code i]', 'input[autocomplete=one-time-code]',
    'input[placeholder*="code" i]', 'input[id*=code i]',
  ];
  const urlReached = page.waitForURL(/\/account\/verify(?:[/?]|$)/i, {
    waitUntil: "domcontentloaded",
    timeout: config.timeoutMs,
  }).then(() => true).catch(() => false);
  const inputReached = page.locator(verifyInputSelectors.join(",")).first().waitFor({
    state: "visible",
    timeout: config.timeoutMs,
  }).then(() => true).catch(() => false);
  const reached = await Promise.race([urlReached, inputReached]);
  if (!reached) {
    const visibleText = (await page.locator("body").innerText().catch(() => "")).replace(/\s+/g, " ").trim();
    throw new Error(`Weee 未进入验证码页面，可能是邮箱域名被拒绝、触发站点反滥用校验或页面未完成加载。当前页面提示：${visibleText.slice(0, 240)}`);
  }
  return true;
}

function interpolate(value, data) {
  return String(value).replace(/\{\{\s*([A-Za-z0-9_$.-]+)\s*\}\}/g, (_, key) => {
    const value = key.split(".").reduce((current, part) => current == null ? undefined : current[part], data);
    return value == null ? "" : String(value);
  });
}

function loadRows() {
  const configuredFile = process.env.BROWSER_DATA_FILE || "protocol-data.json";
  const resolvedFile = configuredFile && path.isAbsolute(configuredFile)
    ? configuredFile
    : path.resolve(process.env.APP_HOME || process.cwd(), configuredFile);
  const file = configuredFile && fs.existsSync(resolvedFile) ? resolvedFile : "";
  if (!file) return Array.from({ length: Math.max(1, Number(process.env.BROWSER_REPEAT || 1)) }, () => ({}));
  const parsed = JSON.parse(fs.readFileSync(file, "utf8"));
  if (!Array.isArray(parsed)) throw new Error("BROWSER_DATA_FILE must contain a JSON array.");
  return parsed;
}

function browserExecutableCandidates() {
  return [
    process.env.BROWSER_EXECUTABLE_PATH,
    process.env.CHROME_PATH,
    process.platform === "darwin" ? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" : "",
    process.platform === "win32" && process.env.PROGRAMFILES ? `${process.env.PROGRAMFILES}\\Google\\Chrome\\Application\\chrome.exe` : "",
    process.platform === "win32" && process.env.LOCALAPPDATA ? `${process.env.LOCALAPPDATA}\\Google\\Chrome\\Application\\chrome.exe` : "",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
    ...(process.env.BROWSER_USE_BUNDLED !== "false" ? [chromium.executablePath()] : []),
  ].filter((candidate, index, all) => candidate && fs.existsSync(candidate) && all.indexOf(candidate) === index);
}

async function launchLocalBrowser() {
  const launchOptions = {
    headless: config.headless,
    args: ["--no-first-run", "--no-default-browser-check", "--disable-dev-shm-usage", "--disable-crash-reporter", "--disable-breakpad"],
    dumpio: process.env.BROWSER_DEBUG === "true",
  };
  const attempts = browserExecutableCandidates().map((executablePath) => ({ executablePath }));
  if (process.env.BROWSER_CHANNEL !== "off") attempts.push({ channel: process.env.BROWSER_CHANNEL || "chrome" });
  const launchErrors = [];
  for (const attempt of attempts) {
    try {
      const browser = await chromium.launch({ ...launchOptions, ...attempt });
      return { browser, remote: false };
    } catch (error) {
      launchErrors.push(`${JSON.stringify(attempt)}: ${error.message}`);
    }
  }
  throw new Error(`Chrome 启动失败。请关闭正在运行的同一 Chrome 后重试，或设置 BROWSER_EXECUTABLE_PATH。\n${launchErrors.join("\n---\n")}`);
}

function selectBrowserPage(context) {
  const pages = context.pages();
  const targetOrigin = new URL(config.cartUrl).origin;
  return pages.find((candidate) => candidate.url().startsWith(targetOrigin)) ||
    pages.find((candidate) => /weee\.com/i.test(candidate.url())) ||
    pages.find((candidate) => candidate.url() === "about:blank") ||
    pages[0];
}

async function launchBitBrowser(data = {}) {
  const browserId = String(data.browserId || config.bitbrowser.browserIds[0] || "").trim();
  if (!browserId) {
    throw new Error("未配置 BitBrowser 浏览器 ID。请在 bitbrowser.config.json 的 browserIds 或 .env 的 BITBROWSER_BROWSER_IDS 中填写。");
  }
  const client = new BitBrowserClient({
    baseUrl: config.bitbrowser.apiUrl,
    timeoutMs: config.bitbrowser.apiTimeoutMs,
  });
  const proxyUrl = String(data.proxyUrl || config.bitbrowser.proxyUrl || "").trim();
  if (proxyUrl) {
    await client.updateProxy(browserId, parseProxyUrl(proxyUrl));
    console.log(`[BitBrowser] 已为窗口 ${browserId} 应用代理配置。`);
  }
  const opened = await client.open(browserId, { queue: config.bitbrowser.queue });
  const endpoint = opened?.ws || opened?.http;
  if (!endpoint) throw new Error(`BitBrowser 打开窗口成功，但响应中没有 ws/http 调试地址（browserId=${browserId}）。`);
  const browser = await chromium.connectOverCDP(endpoint, { timeout: config.timeoutMs });
  const context = browser.contexts()[0];
  if (!context) throw new Error(`已连接 BitBrowser，但没有可用浏览器上下文（browserId=${browserId}）。`);
  const page = selectBrowserPage(context) || await context.newPage();
  return { browser, context, page, remote: true, browserId, client };
}

async function launchAutomationBrowser(data = {}) {
  if (config.provider === "bitbrowser") return launchBitBrowser(data);
  if (config.provider !== "local") {
    throw new Error(`不支持的 BROWSER_PROVIDER：${config.provider}。可用值为 local、bitbrowser。`);
  }
  const launched = await launchLocalBrowser();
  const storageStateValue = process.env.BROWSER_STORAGE_STATE || "";
  const storageStatePath = storageStateValue
    ? (path.isAbsolute(storageStateValue) ? storageStateValue : path.resolve(process.env.APP_HOME || process.cwd(), storageStateValue))
    : "";
  if (storageStatePath) await fs.promises.mkdir(path.dirname(storageStatePath), { recursive: true }).catch(() => {});
  const context = await launched.browser.newContext({
    storageState: storageStatePath && fs.existsSync(storageStatePath) ? storageStatePath : undefined,
  });
  const page = await context.newPage();
  return { ...launched, context, page, storageStatePath };
}

async function clearBrowserData(session) {
  const { browser, context, page } = session;
  await context.clearCookies().catch(() => {});
  for (const candidate of context.pages()) {
    const cdp = await context.newCDPSession(candidate).catch(() => null);
    if (!cdp) continue;
    await cdp.send("Network.clearBrowserCache").catch(() => {});
    await cdp.send("Network.clearBrowserCookies").catch(() => {});
    await cdp.send("Storage.clearDataForOrigin", {
      origin: new URL(config.cartUrl).origin,
      storageTypes: "all",
    }).catch(() => {});
    await cdp.detach().catch(() => {});
  }
  if (session.remote && session.client && session.browserId) {
    await session.client.clearCache(session.browserId).catch((error) => {
      console.warn(`[BitBrowser] 清理窗口缓存失败：${error.message}`);
    });
  }
  await page.goto(config.cartUrl, {
    waitUntil: "domcontentloaded",
    timeout: config.timeoutMs,
  }).catch(() => {});
  await waitForPageSettled(page);
  return browser;
}

async function completeLogin(page, mailApi, mailbox) {
  const loginRequired = await signInAndGetCode(page, mailbox.email);
  if (!loginRequired) {
    console.log("[登录] 当前 BitBrowser 指纹窗口已登录，跳过邮箱登录和验证码。");
    return;
  }
  const existing = await mailApi.listMessages(mailbox);
  const since = Date.now();
  console.log("[邮箱] 等待 Weee 验证邮件，正在通过 API 轮询…");
  const code = await mailApi.waitForCode(mailbox, {
    since,
    ignoreIds: existing.map(m => m.mail_id || m.id || m.message_id || m.messageId).filter(Boolean),
    ignoreFingerprints: existing.map(message => JSON.stringify(message)),
  });
  console.log("[邮箱] 已找到验证码，正在回填（不记录验证码内容）。");
  const codeInputs = page.locator('input[data-testid^="wid-valid-code-input-"]');
  const codeInputCount = await codeInputs.count();
  if (codeInputCount >= code.length) {
    for (let index = 0; index < code.length; index += 1) {
      await codeInputs.nth(index).fill(code[index]);
    }
  } else {
    const codeInput = await firstVisible(page, [
      'input[name*=code i]', 'input[autocomplete=one-time-code]',
      'input[placeholder*="code" i]', 'input[id*=code i]'
    ]);
    if (!codeInput) throw new Error("无法在 Weee 页面找到验证码输入框。");
    await codeInput.fill(code);
  }
  const verify = await firstVisible(page, [
    '[data-testid*="verify"]', 'button:has-text("Verify")',
    'button:has-text("Continue")', 'button:has-text("Log in")',
    'button:has-text("Sign in")'
  ]);
  if (verify) await verify.click();
  const firstCodeInput = codeInputs.first();
  try {
    await firstCodeInput.waitFor({ state: "hidden", timeout: config.timeoutMs });
  } catch {
    throw new Error("验证码已回填，但 Weee 没有确认登录成功。");
  }
  await page.goto(interpolate(config.cartUrl, {}), { waitUntil: "domcontentloaded", timeout: config.timeoutMs });
  await waitForPageSettled(page);
}

async function runPaymentCards(page, data, cards, startIndex = 0) {
  if (!cards.length) {
    return { stage: "payment-form", saved: [], processed: 0, rateLimited: false };
  }
  await openCheckoutPaymentPanel(page, data);
  const saved = [];
  for (const [index, card] of cards.entries()) {
    await openAddCardForm(page);
    const result = await savePaymentCard(page, data, card);
    saved.push({
      ...result,
      index,
      sourceLine: startIndex + index + 1,
      cardLast4: card.cardNumber.slice(-4),
    });
    if (result.rateLimited) {
      return {
        stage: "payment-rate-limited",
        saved,
        processed: index,
        rateLimited: true,
      };
    }
  }
  return { stage: "payment-batch", saved, processed: cards.length, rateLimited: false };
}

async function runBrowserFlow(data = {}) {
  const mailApi = new TempMailApi();
  const session = await launchAutomationBrowser(data);
  const { browser, context, page } = session;
  try {
    const cards = config.checkoutMode === "payment" ? loadPaymentCards() : [];
    if (config.checkoutMode === "payment" && !cards.length) {
      const fallback = paymentData(data);
      assertPaymentData(fallback);
      cards.push({
        raw: `${fallback.cardNumber}|${fallback.expirationDate.slice(0, 2)}|20${fallback.expirationDate.slice(-2)}`,
        cardNumber: fallback.cardNumber,
        expirationDate: fallback.expirationDate,
      });
    }
    if (config.checkoutMode !== "payment") {
      const mailbox = await mailApi.createMailbox();
      console.log(`[邮箱] 已生成 ${mailbox.email}`);
      await completeLogin(page, mailApi, mailbox);
      const checkout = await runCheckoutSteps(page, data);
      return { ok: true, url: page.url(), email: mailbox.email, ...checkout, data };
    }

    const allResults = [];
    let cursor = 0;
    let cycle = 0;
    let rateLimitRestarts = 0;
    while (cursor < cards.length) {
      if (cycle > 0) await clearBrowserData(session);
      console.log(`[支付] 第 ${cycle + 1} 个邮箱周期，最多保存 ${config.paymentMaxSaves} 张卡。`);
      const mailbox = await mailApi.createMailbox();
      console.log(`[邮箱] 已生成 ${mailbox.email}`);
      await completeLogin(page, mailApi, mailbox);
      const batch = cards.slice(cursor, cursor + config.paymentMaxSaves);
      const result = await runPaymentCards(page, data, batch, cursor);
      allResults.push({ email: mailbox.email, ...result });
      cursor += result.processed;
      cycle += 1;
      if (result.rateLimited) {
        rateLimitRestarts += 1;
        if (rateLimitRestarts > config.paymentMaxRateLimitRestarts) {
          throw new Error(`Weee 持续返回绑卡过于频繁，已重开 ${config.paymentMaxRateLimitRestarts} 次仍未恢复。请等待 24 小时或更换浏览器环境后再试。`);
        }
        console.log(`[支付] 检测到 24 小时频繁限制，已处理 ${result.processed} 张，本张卡将换邮箱后重试。`);
        continue;
      }
      rateLimitRestarts = 0;
      if (cursor < cards.length) {
        console.log("[支付] 本周期完成，清理缓存并刷新页面后更换临时邮箱。");
      }
    }
    return { ok: true, url: page.url(), stage: "payment-batches", batches: allResults, data };
  } finally {
    try {
      if (session.storageStatePath) await context.storageState({ path: session.storageStatePath });
    } finally {
      await browser.close();
      if (session.remote && config.bitbrowser.closeOnExit) {
        await session.client.close(session.browserId).catch((error) => {
          console.warn(`[BitBrowser] 关闭窗口失败：${error.message}`);
        });
      }
    }
  }
}

async function main() {
  if (process.argv.includes("--check-package")) {
    const appHome = process.env.APP_HOME || process.cwd();
    const runtimeName = process.platform === "win32" ? "node.exe" : "node";
    const embeddedRuntime = [
      path.join(appHome, ".weee-runtime", "node", runtimeName),
      path.join(appHome, "runtime", runtimeName),
    ].find((candidate) => fs.existsSync(candidate));
    console.log(JSON.stringify({
      packaged: Boolean(process.pkg),
      portable: Boolean(process.pkg) || Boolean(embeddedRuntime),
      nodeRuntime: process.versions.node,
      appHome,
      provider: config.provider,
      browserIds: config.bitbrowser.browserIds.length,
    }, null, 2));
    return;
  }
  if (process.argv.includes("--check-mail-api")) {
    const api = new TempMailApi();
    const mailbox = await api.createMailbox();
    const messages = await api.listMessages(mailbox);
    console.log(`API 连通检查通过：邮箱地址可用，收件箱响应正常（${messages.length} 封邮件）。未打开 Weee 或发送验证码。`);
    return;
  }
  const configuredRows = loadRows();
  const rows = configuredRows.length === 1 &&
    Object.keys(configuredRows[0]).length === 0 &&
    config.provider === "bitbrowser" &&
    config.bitbrowser.browserIds.length > 1
    ? config.bitbrowser.browserIds.map((browserId) => ({ browserId }))
    : configuredRows.map((data, index) => ({
      ...data,
      ...(data.browserId || !config.bitbrowser.browserIds.length
        ? {}
        : { browserId: config.bitbrowser.browserIds[index % config.bitbrowser.browserIds.length] }),
    }));
  const run = async ([index, data]) => {
    try {
      return { index, browserId: data.browserId, ...(await runBrowserFlow(data)) };
    } catch (error) {
      if (process.env.BROWSER_CONTINUE_ON_ERROR !== "true") throw error;
      return { index, browserId: data.browserId, ok: false, error: error.message };
    }
  };
  const results = config.provider === "bitbrowser" && config.bitbrowser.parallel
    ? await Promise.all(rows.map((data, index) => run([index, data])))
    : [];
  if (!results.length) {
    for (const [index, data] of rows.entries()) results.push(await run([index, data]));
  }
  console.log(JSON.stringify(results, null, 2));
}

if (require.main === module) main().catch((error) => {
  console.error(error.stack || error.message);
  process.exitCode = 1;
});

module.exports = {
  config,
  runBrowserFlow,
  main,
  parsePaymentCardLine,
  parseProxyUrl,
  isPaymentAttachUrl,
  isFrequentBindAttempt,
};
